# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 788)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: #150E41;\n"
"    border-radius: 12px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QGroupBox(self.frame)
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setStyleSheet("border: 0;")
        self.header.setTitle("")
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.header)
        self.logo.setMaximumSize(QtCore.QSize(290, 16777215))
        self.logo.setStyleSheet("QLabel{\n"
"     font-size: 26px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;\n"
"}")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.system_btns = QtWidgets.QGroupBox(self.header)
        self.system_btns.setMaximumSize(QtCore.QSize(80, 16777215))
        self.system_btns.setTitle("")
        self.system_btns.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.system_btns.setObjectName("system_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.system_btns)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_hidden_app = QtWidgets.QPushButton(self.system_btns)
        self.btn_hidden_app.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_hidden_app.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_hidden_app.setStyleSheet("QPushButton{\n"
"    color: #150E41;\n"
"    border-radius: 6px;\n"
"    background-color: #C3C4E4;\n"
"}")
        self.btn_hidden_app.setObjectName("btn_hidden_app")
        self.horizontalLayout_2.addWidget(self.btn_hidden_app)
        self.btn_close_app = QtWidgets.QPushButton(self.system_btns)
        self.btn_close_app.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close_app.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_close_app.setStyleSheet("QPushButton{\n"
"    color: #150E41;\n"
"    border-radius: 6px;\n"
"    background-color: #C3C4E4;\n"
"}")
        self.btn_close_app.setObjectName("btn_close_app")
        self.horizontalLayout_2.addWidget(self.btn_close_app)
        self.horizontalLayout.addWidget(self.system_btns)
        self.verticalLayout_2.addWidget(self.header)
        self.main = QtWidgets.QGroupBox(self.frame)
        self.main.setStyleSheet("QGroupBox{\n"
"    border: 0;\n"
"}")
        self.main.setTitle("")
        self.main.setObjectName("main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.build_box = QtWidgets.QGroupBox(self.main)
        self.build_box.setMaximumSize(QtCore.QSize(16777215, 300))
        self.build_box.setTitle("")
        self.build_box.setObjectName("build_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.build_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.build_laber = QtWidgets.QLabel(self.build_box)
        self.build_laber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.build_laber.setStyleSheet("QLabel{\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;\n"
"}")
        self.build_laber.setAlignment(QtCore.Qt.AlignCenter)
        self.build_laber.setObjectName("build_laber")
        self.verticalLayout_5.addWidget(self.build_laber)
        self.content_box = QtWidgets.QGroupBox(self.build_box)
        self.content_box.setTitle("")
        self.content_box.setObjectName("content_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.content_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.input_box = QtWidgets.QGroupBox(self.content_box)
        self.input_box.setTitle("")
        self.input_box.setObjectName("input_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.input_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_8 = QtWidgets.QGroupBox(self.input_box)
        self.groupBox_8.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.input_project_repo = QtWidgets.QLineEdit(self.groupBox_8)
        self.input_project_repo.setStyleSheet("color: #2A313C;")
        self.input_project_repo.setText("")
        self.input_project_repo.setObjectName("input_project_repo")
        self.verticalLayout_9.addWidget(self.input_project_repo)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.input_box)
        self.groupBox_9.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.input_builder_repo = QtWidgets.QLineEdit(self.groupBox_9)
        self.input_builder_repo.setStyleSheet("color: #2A313C;")
        self.input_builder_repo.setText("")
        self.input_builder_repo.setObjectName("input_builder_repo")
        self.verticalLayout_10.addWidget(self.input_builder_repo)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.btn_start_build = QtWidgets.QPushButton(self.input_box)
        self.btn_start_build.setObjectName("btn_start_build")
        self.verticalLayout_8.addWidget(self.btn_start_build)
        self.verticalLayout_6.addWidget(self.input_box)
        self.loading_box = QtWidgets.QGroupBox(self.content_box)
        self.loading_box.setMinimumSize(QtCore.QSize(0, 30))
        self.loading_box.setMaximumSize(QtCore.QSize(16777215, 60))
        self.loading_box.setTitle("")
        self.loading_box.setObjectName("loading_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.loading_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.buil_progress = QtWidgets.QProgressBar(self.loading_box)
        self.buil_progress.setStyleSheet("QProgressBar{\n"
"    background-color: #C3C4E4;\n"
"     border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 101, 255));\n"
"     border-radius: 10px;\n"
"}")
        self.buil_progress.setProperty("value", 0)
        self.buil_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.buil_progress.setObjectName("buil_progress")
        self.verticalLayout_7.addWidget(self.buil_progress)
        self.lebel_build_status = QtWidgets.QLabel(self.loading_box)
        self.lebel_build_status.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.lebel_build_status.setText("")
        self.lebel_build_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lebel_build_status.setObjectName("lebel_build_status")
        self.verticalLayout_7.addWidget(self.lebel_build_status)
        self.verticalLayout_6.addWidget(self.loading_box)
        self.verticalLayout_5.addWidget(self.content_box)
        self.verticalLayout_4.addWidget(self.build_box)
        self.groupBox_4 = QtWidgets.QGroupBox(self.main)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.send_to_back_box_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.send_to_back_box_2.setTitle("")
        self.send_to_back_box_2.setObjectName("send_to_back_box_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.send_to_back_box_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.send_to_back_laber_2 = QtWidgets.QLabel(self.send_to_back_box_2)
        self.send_to_back_laber_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.send_to_back_laber_2.setStyleSheet("QLabel{\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;\n"
"}")
        self.send_to_back_laber_2.setAlignment(QtCore.Qt.AlignCenter)
        self.send_to_back_laber_2.setObjectName("send_to_back_laber_2")
        self.verticalLayout_13.addWidget(self.send_to_back_laber_2)
        self.content_box_2 = QtWidgets.QGroupBox(self.send_to_back_box_2)
        self.content_box_2.setTitle("")
        self.content_box_2.setObjectName("content_box_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.content_box_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.input_box_2 = QtWidgets.QGroupBox(self.content_box_2)
        self.input_box_2.setTitle("")
        self.input_box_2.setObjectName("input_box_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.input_box_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_10 = QtWidgets.QGroupBox(self.input_box_2)
        self.groupBox_10.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.input_nickname = QtWidgets.QLineEdit(self.groupBox_10)
        self.input_nickname.setStyleSheet("color: #2A313C;")
        self.input_nickname.setText("")
        self.input_nickname.setObjectName("input_nickname")
        self.verticalLayout_16.addWidget(self.input_nickname)
        self.verticalLayout_15.addWidget(self.groupBox_10)
        self.groupBox = QtWidgets.QGroupBox(self.input_box_2)
        self.groupBox.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.input_repo_name = QtWidgets.QLineEdit(self.groupBox)
        self.input_repo_name.setStyleSheet("color: #2A313C;")
        self.input_repo_name.setObjectName("input_repo_name")
        self.verticalLayout_11.addWidget(self.input_repo_name)
        self.verticalLayout_15.addWidget(self.groupBox)
        self.groupBox_11 = QtWidgets.QGroupBox(self.input_box_2)
        self.groupBox_11.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.input_server_endpoint = QtWidgets.QLineEdit(self.groupBox_11)
        self.input_server_endpoint.setStyleSheet("color: #2A313C;")
        self.input_server_endpoint.setText("")
        self.input_server_endpoint.setObjectName("input_server_endpoint")
        self.verticalLayout_17.addWidget(self.input_server_endpoint)
        self.verticalLayout_15.addWidget(self.groupBox_11)
        self.btn_send_to_back = QtWidgets.QPushButton(self.input_box_2)
        self.btn_send_to_back.setObjectName("btn_send_to_back")
        self.verticalLayout_15.addWidget(self.btn_send_to_back)
        self.verticalLayout_14.addWidget(self.input_box_2)
        self.loading_box_2 = QtWidgets.QGroupBox(self.content_box_2)
        self.loading_box_2.setMinimumSize(QtCore.QSize(0, 30))
        self.loading_box_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.loading_box_2.setTitle("")
        self.loading_box_2.setObjectName("loading_box_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.loading_box_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.send_progress = QtWidgets.QProgressBar(self.loading_box_2)
        self.send_progress.setStyleSheet("QProgressBar{\n"
"    background-color: #C3C4E4;\n"
"     border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 101, 255));\n"
"     border-radius: 10px;\n"
"}")
        self.send_progress.setProperty("value", 0)
        self.send_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.send_progress.setObjectName("send_progress")
        self.verticalLayout_18.addWidget(self.send_progress)
        self.lebel_send_status_2 = QtWidgets.QLabel(self.loading_box_2)
        self.lebel_send_status_2.setStyleSheet("    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #EFF2F7;")
        self.lebel_send_status_2.setText("")
        self.lebel_send_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lebel_send_status_2.setObjectName("lebel_send_status_2")
        self.verticalLayout_18.addWidget(self.lebel_send_status_2)
        self.verticalLayout_14.addWidget(self.loading_box_2)
        self.verticalLayout_13.addWidget(self.content_box_2)
        self.verticalLayout_3.addWidget(self.send_to_back_box_2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_2.addWidget(self.main)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "🚀ReleaseMaker🚀"))
        self.btn_hidden_app.setText(_translate("MainWindow", "_"))
        self.btn_close_app.setText(_translate("MainWindow", "X"))
        self.build_laber.setText(_translate("MainWindow", "сборка проекта"))
        self.groupBox_8.setTitle(_translate("MainWindow", "репозиторий проекта"))
        self.groupBox_9.setTitle(_translate("MainWindow", "репозиторий сборки(github only)"))
        self.btn_start_build.setText(_translate("MainWindow", "начать сборку"))
        self.send_to_back_laber_2.setText(_translate("MainWindow", "отправка сборок на сервер"))
        self.groupBox_10.setTitle(_translate("MainWindow", "гитхаб никнэйм"))
        self.groupBox.setTitle(_translate("MainWindow", "названеи репозитория"))
        self.groupBox_11.setTitle(_translate("MainWindow", "ручка бэка для загрузки сборок"))
        self.btn_send_to_back.setText(_translate("MainWindow", "начать загрузку на бэк"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
